### ISSUE TITLE
[Roadmap] Infrastructure

### ISSUE THREAD

**Issue by johnyob** [johnyob/dromedary#34]
Issues related to Dromedary's infrastructure (such as testing, utilities, etc)

- [ ] Refactoring Project Structure
- [ ] Switching to testing libraries to Jane Street libraries
  - [ ] Switching `Alcotest` to inline tests
  - [ ] Switching `QCheck` to `Quickcheck`   
- [ ]  Replace pretty printing utility library with `Fmt`
