### ISSUE TITLE
[Roadmap] Constraints Library

### ISSUE THREAD

**Issue by johnyob** [johnyob/dromedary#35]
Issues related to Dromedary's `Constraints` library.

- [ ] Split `Constraints` library into `Constraints` and `Unifier`
- [ ] Add error handling into the Constraints library
- [ ] Add transactions ("Snapshots") to `Unifier`
- [ ] Add monadic primitives to `Constraints` library

Potential (*less concrete*) issues include:
 - Abstracting `Constraints` further to avoid reliance on generalization, by abstracting the solving of first-order let abstractions.
