### ISSUE TITLE
[Roadmap] Error Reporting

### ISSUE THREAD

**Issue by johnyob** [johnyob/dromedary#39]
Issues related to improving the error reporting of Dromedary. 

- [ ] Add locations to `Parsing` library
- [ ] Add locations to `Constraints` library
- [ ] Add error handling to `Constraints` library
- [ ] Improve error reports using [pp_loc](https://www.github.com/johnyob/pp_loc)
